### ISSUE TITLE
New user scenario passes only once

### ISSUE THREAD

**Issue by greens82** [Behat/ChainedStepsExtension#5]

**Comment by stof** [comment]
This extension was a PoC to see whether it was possible to provide a compatibility layer for the Behat 2.x feature for Behat 3 users. but it has been implemented for the early Behat 3 beta versions, and Behat 3 was hugely refactored between beta (nearly a complete rewrite compared to the initial Behat 3 beta).
This extension was updated to be compatible with the final Behat 3 codebase, but the implementation does not work. And given that I don't use chained steps (and that they are a bad idea in the first place, which is why they have been removed from Behat 3), I haven't tried to make the extension work, considering that my time would be better spent on other things.
My recommendation is to stop using chained steps.

Feel free to contribute to this extension to try making it work though if you really want to make the compatibility layer available.
We have a testsuite in place, which is currently failing because of the issues in the current implementation. If you manage to make it green, it means it will be working.

**Comment by stof** [comment]
I'm closing this issue. This experiment has been abandoned years ago.
